dist: xenial
language: ruby
branches:
  except:
    - "/^v\\d/"
env:
  global:
    - PACKER_VERSION=1.3.3
    - SC_VERSION=stable # or "v0.4.7", or "latest"
  matrix:
    - AMI=prometheus
    - AMI=unifi
install:
  # Install a custom version of shellcheck instead of Travis CI's default
  - |
    wget "https://storage.googleapis.com/shellcheck/shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
    tar --xz -xvf "shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
    shellcheck() { "shellcheck-${SC_VERSION}/shellcheck" "$@"; }
    shellcheck --version
  # Install PIP packages
  - |
    pip install --user --upgrade ansible awscli aws-amicleaner future
    ansible --version
    aws --version
    amicleaner --version
  # Install Hashicorp's Packer
  - |
    curl -L -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
    unzip -d ~/bin packer.zip
    packer version
before_script:
  - |
    . <( ( echo "$ENCRYPT_KEY" | base64 --decode ) |  gpg --batch --yes --decrypt --passphrase-fd 0 .env.gpg ) 2>/dev/null || true
    if [[ "$TRAVIS_BRANCH" == master && "$TRAVIS_PULL_REQUEST" == false ]]; then
    aws configure --profile default set aws_access_key_id "${TRAVIS_AWS_ACCESS_KEY_ID}"
    aws configure --profile default set aws_secret_access_key "${TRAVIS_AWS_SECRET_ACCESS_KEY}"
      case "$AMI" in
        prometheus )
          aws configure --profile orion set role_arn "${TRAVIS_AWS_ORION_ROLE_ARN}"
          aws configure --profile orion set source_profile default
          aws configure --profile orion set region us-east-1
          ;;
        unifi )
          aws configure --profile mec7 set role_arn "${TRAVIS_AWS_MEC7_ROLE_ARN}"
          aws configure --profile mec7 set source_profile default
          aws configure --profile mec7 set region us-west-2
          ;;
      esac
    fi
  - git clone https://github.com/vghn/ansible ../ansible
  - ansible-galaxy install --roles-path ../ansible/roles/galaxy --role-file ../ansible/roles/requirements.yml

script:
  - find ./bin ./shlib -type f -exec shellcheck {} +
  - ./bin/ami validate "${AMI}"
  - |
    if [[ "$TRAVIS_BRANCH" == master && "$TRAVIS_PULL_REQUEST" == false ]]; then
      ./bin/ami build "${AMI}" && ./bin/ami clean "${AMI}"
    fi

notifications:
  webhooks:
    urls: https://vbot.ghn.me/travis
  slack:
    secure: I5d4t/2F8KHgP2Z0ajUz6CIS6TZdMUkFYUa5wH3uxyXiPlJpKZh0E5jsh7Tdz356RDOs5r/lGCzetqmlhH7EwmtiV1tks+btZ+hmR+xYFgmhMwnXivzWn1MwBtpt1q9pqCgheMODmcA8vG3yGeLooStLQ3++gjAGVWV2v9jahz5zoKrkYw+4haS+EzpsPddtMQx8/AiiMuB3MGOHZKvCmRjQW72MFqN2SYKT9U3MzBgdJS8Mxa7axITmyu1Pxvgt9kYJQilHbBUqNJUL1W9lBugFtVDMECHUC7DO5blFwbzUhglUDn9hhOy8VisHqrFuiNydFcgnqHoQJ+Fj3wKIukzPMpru1ZmcBC/wmNXwaAKIRlqzNYy9tfJOk/sjUkJ34BjNtf+8OAoRgRxfYycoZ0eXLidfZ/43PBuW5jP1pQK1Gk7yFLGyM2yOXTqflIGa2I71i87cxqE38laOspP3+SAtl0bIP3d8uDr/FBWb8hHTB9PyA0pmDTjy/vzcnH8KqMDs/OIAwoCs3rNnb/I0nhONBWU7sLMmJjqMr/AhA39AMxOXFd/9xZyVP2iHu0RueLFrOH6ZBrFUgUEGyn4uqPc2Z0wsO6wox4puM8YHH7YP/Z/GnfM/zMiX5rg4UOarUX3zWrUNPSSP0Z+gREgIvbBV/IYiqhqscq49eB1+mk0=
